import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/Container";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import dynamic from "next/dynamic";

// Dynamically import ReduxProvider without SSR
const ReduxProvider = dynamic(() => import("@/redux/ReduxProvider"), {
  ssr: false
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-zinc-900 bg-zinc-100 min-h-screen`}>
        <ReduxProvider>
          <Container>
            <Header />
            {children}
            <Footer />
          </Container>
        </ReduxProvider>
      </body>
    </html>
  );
}
